---
title: "Decathlon Data Analysis"
output: html_notebook
---

```{r}
library(tidyverse)

decathlon <- read_rds("/Users/codeclanstudent/codeclan_projects/dirty_data_project_karolina/task1/clean_data/decathlon.rds")
```


1. Athlete with longest long jump seen in the data

```{r}
decathlon %>%
  select(athlete, long_jump) %>% 
  slice_max(long_jump)
```
2. Average 100m time per competition

```{r}
decathlon %>% 
  group_by(competition) %>%
  summarise(avg_100m_time = mean(sprint_100m))
  
```

3. Athlete with the highest total points across both competitions

```{r}
decathlon %>% 
  group_by(competition) %>% 
  slice_max(points) %>% 
  select(athlete, points, competition)
  
```

4. The shot-put scores for the top three competitors in each competition

```{r}
decathlon %>% 
  group_by(competition) %>% 
  filter(rank %in% c(1, 2, 3)) %>% 
  select(athlete, shot_put, competition)
```
5. The average points for competitors who ran the 400m in less than 50 seconds vs. those than ran 400m in more than 50 seconds.

```{r}
decathlon %>% 
  group_by(sprint_400m < 50) %>% 
  summarise(avg_points = mean(points))
  
```


